/**
 * The whole build, in place of Vite.
 *
 * Three jobs, in order, because each depends on the one before:
 *
 *  1. Bundle the browser entry. Content-hashed, so the CSS and JS can be
 *     cached hard, and the hashes are not known until this finishes.
 *  2. Write those hashes into src/server/manifest.generated.ts, which is what
 *     the server renders into `<link>` and `<script>`, and a copy beside the
 *     bundle. tests/assets.test.ts checks the two agree with what is on disk.
 *  3. Bundle src/node.ts, the self-hosted entry. The Worker is not bundled
 *     here - `wrangler deploy` does that from src/worker.ts.
 *
 * Then `public/` is copied over the client output. That is what puts the
 * favicons, the Open Graph image, and Scalar's vendored bundle where both
 * targets serve them from; nothing else does it now.
 */
import { mkdir, readdir, rm } from "node:fs/promises";
import { MANIFEST_FILENAME } from "../src/server/assets.ts";

const OUT = "dist";
const CLIENT_OUT = `${OUT}/client`;
const SERVER_OUT = `${OUT}/server`;
/** Where src/node.ts serves the client bundle from, relative to the CWD. */
const CLIENT_DIR = `./${CLIENT_OUT}`;
const GENERATED = "src/server/manifest.generated.ts";

const minify = process.env["BUILD_DEBUG"] !== "1";

function fail(message: string, logs: readonly unknown[] = []): never {
  console.error(message);
  for (const entry of logs) console.error(String(entry));
  process.exit(1);
}

async function buildClient(): Promise<{ script: string; stylesheet: string }> {
  const result = await Bun.build({
    entrypoints: ["src/client/entry.tsx"],
    outdir: CLIENT_OUT,
    target: "browser",
    minify,
    sourcemap: "linked",
    // `hono/jsx/dom` is the smaller browser runtime; the server build uses
    // the isomorphic `hono/jsx`. Source-compatible, so the same components
    // render on both sides and hydration lines up.
    tsconfig: "tsconfig.client.json",
    define: { "process.env.NODE_ENV": '"production"' },
    naming: { entry: "[name]-[hash].[ext]", asset: "[name]-[hash].[ext]" },
  });

  const publicPath = (path: string) => `/${path.split(`${CLIENT_OUT}/`)[1]}`;
  const script = result.outputs.find((o) => o.kind === "entry-point");
  const stylesheet = result.outputs.find((o) => o.path.endsWith(".css"));
  if (script === undefined) fail("client bundle emitted no entry point");
  if (stylesheet === undefined) fail("client bundle emitted no stylesheet");

  return {
    script: publicPath(script.path),
    stylesheet: publicPath(stylesheet.path),
  };
}
/**
 * Only the self-hosted entry is bundled here. The Worker is left to
 * `wrangler deploy`, whose own esbuild pass is the thing that understands
 * `nodejs_compat`, the `cloudflare:workers` module, and workerd's resolution
 * conditions - reimplementing that with Bun buys nothing and gets it wrong.
 *
 * A single file, so the runtime image copies `dist/` and needs neither the
 * source tree nor `node_modules`.
 */
async function buildServer(): Promise<void> {
  const result = await Bun.build({
    entrypoints: ["src/node.ts"],
    outdir: SERVER_OUT,
    target: "bun",
    minify,
    naming: { entry: "index.js" },
  });
  if (!result.success) fail("server bundle failed", result.logs);
}

/** Everything in public/ lands at the web root, favicons and all. */
async function copyPublic(dir = "public", prefix = ""): Promise<number> {
  let copied = 0;
  for (const item of await readdir(dir, { withFileTypes: true })) {
    const from = `${dir}/${item.name}`;
    const to = `${CLIENT_OUT}/${prefix}${item.name}`;
    if (item.isDirectory()) {
      copied += await copyPublic(from, `${prefix}${item.name}/`);
      continue;
    }
    await Bun.write(to, Bun.file(from));
    copied += 1;
  }
  return copied;
}

await rm(OUT, { recursive: true, force: true });
await mkdir(CLIENT_OUT, { recursive: true });

const assets = await buildClient();

await Bun.write(
  GENERATED,
  `// Generated by scripts/build.ts. Do not edit; do not commit.\n` +
    `import type { AssetManifest } from "./assets.ts";\n\n` +
    `export const ASSETS: AssetManifest = ${JSON.stringify(assets, null, 2)};\n\n` +
    `/** Where src/node.ts serves the client bundle from. */\n` +
    `export const CLIENT_DIR = ${JSON.stringify(CLIENT_DIR)};\n`,
);

// The manifest is also written beside the bundle so a deployment can be
// checked without the source tree, and so tests can assert the two agree.
await Bun.write(
  `${CLIENT_OUT}/${MANIFEST_FILENAME}`,
  `${JSON.stringify(assets, null, 2)}\n`,
);

await buildServer();

const copied = await copyPublic();

console.log(`client   ${assets.script}`);
console.log(`         ${assets.stylesheet}`);
console.log(`public   ${copied} files -> ${CLIENT_OUT}`);
console.log(`server   ${SERVER_OUT}/index.js`);
console.log(`worker   src/worker.ts (bundled by wrangler at deploy)`);
