/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as ApiPlansRouteImport } from "./routes/api/plans";
import { Route as ApiPlansIdRouteImport } from "./routes/api/plans.$id";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as HealthzRouteImport } from "./routes/healthz";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as PPlanIdRouteImport } from "./routes/p.$planId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const HealthzRoute = HealthzRouteImport.update({
  id: "/healthz",
  path: "/healthz",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiPlansRoute = ApiPlansRouteImport.update({
  id: "/api/plans",
  path: "/api/plans",
  getParentRoute: () => rootRouteImport,
} as any);
const PPlanIdRoute = PPlanIdRouteImport.update({
  id: "/p/$planId",
  path: "/p/$planId",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiPlansIdRoute = ApiPlansIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => ApiPlansRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/healthz": typeof HealthzRoute;
  "/api/plans": typeof ApiPlansRouteWithChildren;
  "/p/$planId": typeof PPlanIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/plans/$id": typeof ApiPlansIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/healthz": typeof HealthzRoute;
  "/api/plans": typeof ApiPlansRouteWithChildren;
  "/p/$planId": typeof PPlanIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/plans/$id": typeof ApiPlansIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/healthz": typeof HealthzRoute;
  "/api/plans": typeof ApiPlansRouteWithChildren;
  "/p/$planId": typeof PPlanIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/plans/$id": typeof ApiPlansIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/healthz"
    | "/api/plans"
    | "/p/$planId"
    | "/api/auth/$"
    | "/api/plans/$id";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/dashboard"
    | "/healthz"
    | "/api/plans"
    | "/p/$planId"
    | "/api/auth/$"
    | "/api/plans/$id";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/healthz"
    | "/api/plans"
    | "/p/$planId"
    | "/api/auth/$"
    | "/api/plans/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRoute;
  HealthzRoute: typeof HealthzRoute;
  ApiPlansRoute: typeof ApiPlansRouteWithChildren;
  PPlanIdRoute: typeof PPlanIdRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/healthz": {
      id: "/healthz";
      path: "/healthz";
      fullPath: "/healthz";
      preLoaderRoute: typeof HealthzRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/plans": {
      id: "/api/plans";
      path: "/api/plans";
      fullPath: "/api/plans";
      preLoaderRoute: typeof ApiPlansRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/p/$planId": {
      id: "/p/$planId";
      path: "/p/$planId";
      fullPath: "/p/$planId";
      preLoaderRoute: typeof PPlanIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/plans/$id": {
      id: "/api/plans/$id";
      path: "/$id";
      fullPath: "/api/plans/$id";
      preLoaderRoute: typeof ApiPlansIdRouteImport;
      parentRoute: typeof ApiPlansRoute;
    };
  }
}

interface ApiPlansRouteChildren {
  ApiPlansIdRoute: typeof ApiPlansIdRoute;
}

const ApiPlansRouteChildren: ApiPlansRouteChildren = {
  ApiPlansIdRoute: ApiPlansIdRoute,
};

const ApiPlansRouteWithChildren = ApiPlansRoute._addFileChildren(
  ApiPlansRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HealthzRoute: HealthzRoute,
  ApiPlansRoute: ApiPlansRouteWithChildren,
  PPlanIdRoute: PPlanIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";
import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
